language: cpp

sudo:
    - required

git:
  submodules: false

os:
  - linux

compiler:
  - g++

branches:
  only:
    - master

before_install:
  - sudo apt install libeigen3-dev libeigen3-doc
  - sudo apt install libgtest-dev
  - "BUILD_ROOT=$(pwd); cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib; cd ${BUILD_ROOT}"

install:
  - cd test
  - cmake .
  - make
  - cd ../

script:
  - ./ci.sh
